"""empty message

Revision ID: a8f5b4a1c196
Revises: 65b29295cbfa
Create Date: 2022-03-07 02:03:14.033475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f5b4a1c196'
down_revision = '65b29295cbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('products', 'product_id')
    # ### end Alembic commands ###
